import React, { useState, useRef, useEffect } from 'react';
import type { ScanResultData } from '../types';
import { ShieldCheck, AlertTriangle, ShieldAlert, HelpCircle, ArrowLeft, CheckCircle2, Info, AlertOctagon, ExternalLink, Download, FileText, FileCode, Printer, ChevronDown } from 'lucide-react';
import { downloadMalVisionPdfReport } from './HistoryModal';

interface ScanResultProps {
  result: ScanResultData;
  onNewScan: () => void;
}

export const ScanResult: React.FC<ScanResultProps> = ({ result, onNewScan }) => {
  const [downloadMenuOpen, setDownloadMenuOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setDownloadMenuOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const getStatusBadge = () => {
    switch (result.status) {
      case 'Safe':
        return (
          <div className="flex items-center space-x-1.5 px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800 text-xs font-semibold">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Safe</span>
          </div>
        );
      case 'Suspicious':
        return (
          <div className="flex items-center space-x-1.5 px-3 py-1 rounded-full bg-amber-100 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border border-amber-300 dark:border-amber-800 text-xs font-semibold">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Suspicious</span>
          </div>
        );
      case 'Malicious':
        return (
          <div className="flex items-center space-x-1.5 px-3 py-1 rounded-full bg-rose-100 dark:bg-rose-950/60 text-rose-800 dark:text-rose-300 border border-rose-300 dark:border-rose-800 text-xs font-semibold">
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>Malicious</span>
          </div>
        );
      case 'Unknown':
      default:
        return (
          <div className="flex items-center space-x-1.5 px-3 py-1 rounded-full bg-neutral-100 dark:bg-neutral-800 text-neutral-700 dark:text-neutral-300 border border-neutral-300 dark:border-neutral-700 text-xs font-semibold">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Unknown</span>
          </div>
        );
    }
  };

  const getFindingIcon = (type: string) => {
    switch (type) {
      case 'danger': return <AlertOctagon className="w-4 h-4 text-rose-500 flex-shrink-0 mt-0.5" />;
      case 'warning': return <AlertTriangle className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5" />;
      case 'success': return <CheckCircle2 className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />;
      case 'info': default: return <Info className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />;
    }
  };

  const isUrl = result.targetType === 'url' || result.target.startsWith('http://') || result.target.startsWith('https://');

  // Report Export Handlers
  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(result, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `malvision_report_${result.id || 'scan'}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    setDownloadMenuOpen(false);
  };

  const handleDownloadTXT = () => {
    const reportText = `====================================================
MALVISION THREAT DETECTION REPORT
====================================================
Target: ${result.target}
Type: ${result.targetType.toUpperCase()}
Status: ${result.status.toUpperCase()}
Timestamp: ${result.timestamp || new Date().toLocaleString()}
Report ID: ${result.id}

ASSESSMENT EXPLANATION:
${result.explanation}

RECOMMENDED ACTION:
${result.recommendedAction}

KEY FINDINGS:
${result.findings.map(f => `- [${f.type.toUpperCase()}] ${f.title}: ${f.detail}`).join('\n')}

====================================================
Generated by MalVision Threat Intelligence (https://malvision.vercel.app)
====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.href = url;
    downloadAnchor.download = `malvision_report_${result.id || 'scan'}.txt`;
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    URL.revokeObjectURL(url);
    setDownloadMenuOpen(false);
  };

  const handlePrintPDF = () => {
    setDownloadMenuOpen(false);
    downloadMalVisionPdfReport(result);
  };

  return (
    <div className="w-full h-full flex flex-col justify-between overflow-y-auto pr-1 text-left space-y-4">
      {/* Header Row: Target & Status & Download Dropdown */}
      <div className="flex items-center justify-between border-b border-neutral-200/80 dark:border-neutral-800 pb-3 gap-3">
        <div className="truncate flex-1 min-w-0">
          <span className="text-[11px] font-semibold uppercase tracking-wider text-neutral-400">Target Analyzed</span>
          {isUrl ? (
            <a
              href={result.target}
              target="_blank"
              rel="noopener noreferrer"
              className="text-base font-bold text-blue-600 dark:text-blue-400 hover:underline flex items-center space-x-1.5 truncate max-w-xs sm:max-w-md group"
            >
              <span className="truncate">{result.target}</span>
              <ExternalLink className="w-3.5 h-3.5 flex-shrink-0 opacity-70 group-hover:opacity-100 transition" />
            </a>
          ) : (
            <h3 className="text-base font-bold text-neutral-900 dark:text-white truncate max-w-xs sm:max-w-md">
              {result.target}
            </h3>
          )}
        </div>

        <div className="flex items-center space-x-2 shrink-0">
          {getStatusBadge()}

          {/* Download Options Dropdown */}
          <div className="relative" ref={dropdownRef}>
            <button
              onClick={() => setDownloadMenuOpen(!downloadMenuOpen)}
              className="px-3 py-1.5 rounded-full bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 text-xs font-semibold hover:opacity-90 transition cursor-pointer flex items-center space-x-1.5 shadow-xs"
              title="Download Threat Report"
            >
              <Download className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Download Report</span>
              <ChevronDown className="w-3 h-3 opacity-70" />
            </button>

            {downloadMenuOpen && (
              <div className="absolute right-0 mt-2 w-44 rounded-2xl bg-white dark:bg-[#18181D] shadow-xl border border-neutral-200 dark:border-neutral-800 p-1.5 z-50 animate-in fade-in slide-in-from-top-1 duration-150 space-y-0.5">
                <button
                  onClick={handleDownloadJSON}
                  className="w-full flex items-center space-x-2.5 px-3 py-2 rounded-xl text-xs font-semibold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-800/80 transition cursor-pointer"
                >
                  <FileCode className="w-4 h-4 text-emerald-500" />
                  <span>Download JSON</span>
                </button>

                <button
                  onClick={handleDownloadTXT}
                  className="w-full flex items-center space-x-2.5 px-3 py-2 rounded-xl text-xs font-semibold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-800/80 transition cursor-pointer"
                >
                  <FileText className="w-4 h-4 text-blue-500" />
                  <span>Download Text (.txt)</span>
                </button>

                <button
                  onClick={handlePrintPDF}
                  className="w-full flex items-center space-x-2.5 px-3 py-2 rounded-xl text-xs font-semibold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-800/80 transition cursor-pointer"
                >
                  <Printer className="w-4 h-4 text-rose-500" />
                  <span>Download PDF Certificate</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Primary Summary & Explanation */}
      <div className="space-y-2 bg-neutral-50 dark:bg-neutral-800/40 p-3.5 rounded-xl border border-neutral-200/60 dark:border-neutral-700/60">
        <h4 className="text-xs font-semibold text-neutral-700 dark:text-neutral-300">Assessment Explanation</h4>
        <p className="text-xs text-neutral-600 dark:text-neutral-300 leading-relaxed">
          {result.explanation}
        </p>
      </div>

      {/* Findings List */}
      <div className="space-y-2">
        <h4 className="text-xs font-semibold text-neutral-500 uppercase tracking-wider">Key Findings</h4>
        <div className="space-y-1.5 max-h-32 overflow-y-auto pr-1">
          {result.findings.map((finding, idx) => (
            <div key={idx} className="flex items-start space-x-2.5 p-2 rounded-lg bg-white dark:bg-neutral-800 border border-neutral-200/50 dark:border-neutral-700/50 text-xs">
              {getFindingIcon(finding.type)}
              <div>
                <span className="font-semibold text-neutral-900 dark:text-white">{finding.title}: </span>
                <span className="text-neutral-600 dark:text-neutral-400">{finding.detail}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recommended Action & Reset Button */}
      <div className="pt-2 border-t border-neutral-200/80 dark:border-neutral-800 flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="text-xs text-neutral-600 dark:text-neutral-400 flex items-center space-x-2">
          <span className="font-semibold text-neutral-900 dark:text-white">Recommended Action:</span>
          <span>{result.recommendedAction}</span>
        </div>

        <button
          onClick={onNewScan}
          className="px-4 py-2 text-xs font-medium rounded-full bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 hover:opacity-90 transition cursor-pointer flex items-center space-x-1.5 flex-shrink-0"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>New Scan</span>
        </button>
      </div>
    </div>
  );
};
